language: java
jdk:
    - oraclejdk8
    - oraclejdk11
    - openjdk11
    - openjdk-ea

matrix:
    allow_failures:
        - jdk: openjdk-ea
    include:
        - jdk: openjdk10
        before_install:
            - rm "${JAVA_HOME}/lib/security/cacerts"
            - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

notifications:
    email: marcfreir@yandex.com